title: Web Developer
email: pro@kmaschta.me
description: > #
baseurl: ""
url: "https://www.kmaschta.me"
twitter: Kmaschta
github: Kmaschta

# Build settings
markdown: kramdown
kramdown:
    input: GFM
theme: minima

exclude:
    - Gemfile
    - Gemfile.lock
    - Makefile
    - README.md
