title: Web Developer
email: pro@kmaschta.me
description: > #
baseurl: ""
url: "https://www.kmaschta.me"
twitter: Kmaschta
github: Kmaschta
stackoverflow: users/3868326/kmaschta
linkedin: kmaschta
gmail: kevin.maschtaler@gmail.com
google_analytics_ua: UA-83286822-1

# Build settings
markdown: kramdown
kramdown:
    input: GFM
theme: minima

exclude:
    - Gemfile
    - Gemfile.lock
    - Makefile
    - README.md
